# Generated by Django 2.2 on 2020-04-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieTime', '0002_auto_20200419_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
