# Generated by Django 2.2 on 2020-04-20 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movieTime', '0004_auto_20200420_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shows',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
