# Generated by Django 2.2 on 2020-04-21 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieTime', '0005_auto_20200420_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(choices=[('G', 'Gold'), ('S', 'Silver')], default='G', max_length=1)),
                ('number', models.PositiveIntegerField(default=1)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieTime.Shows')),
            ],
        ),
    ]
