# Generated by Django 2.2 on 2020-04-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieTime', '0006_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='gold_seats',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shows',
            name='silver_seats',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
