# Generated by Django 2.2 on 2020-04-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieTime', '0008_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_type',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
