# Generated by Django 2.2 on 2020-04-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieTime', '0009_auto_20200421_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_type',
            field=models.CharField(max_length=15),
        ),
    ]
