# Generated by Django 2.2 on 2020-04-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieTime', '0010_auto_20200421_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.PositiveIntegerField(default=0)),
                ('card_type', models.CharField(choices=[('CR', 'Credit'), ('DB', 'Debit')], default='CR', max_length=2)),
                ('cvv', models.PositiveIntegerField(default=0)),
                ('expiry_month', models.PositiveIntegerField(default=0)),
                ('expiry_year', models.PositiveIntegerField(default=0)),
                ('holder_name', models.CharField(max_length=50)),
            ],
        ),
    ]
