# Generated by Django 2.2 on 2020-04-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieTime', '0011_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_type',
            field=models.CharField(max_length=8),
        ),
    ]
