# Generated by Django 2.2 on 2020-04-22 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieTime', '0012_auto_20200422_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ticket',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='movieTime.Ticket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
