# Generated by Django 2.2 on 2020-04-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieTime', '0013_auto_20200422_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
